"""Item -> product-photo mapping for the counter sales manual.

PHOTO_QUERIES maps a photo key to the web image-search query used to find a
real product photo. ITEM_PHOTO maps each manual item name to its photo key —
size/colour variants of the same product share one photo (the label chip on
the card shows the size), which keeps searches accurate.

Brands are the ones visible on the shop shelves: MAGIK, PRITAM (Alfa /
Silver / Vita), HEERA, RK Gold, Z4 Kabel, VELOX, Aastha, Polonix, Florex,
Stronx, Star-Flex, Kamla, Ultima.
"""

PHOTO_QUERIES = {
    # --- mains / metering -------------------------------------------------
    "main_switch_32a":   "32A TPN main switch iron clad",
    "main_switch_16a":   "16A SPN DP iron clad main switch",
    "energy_meter":      "single phase LCD digital energy meter kWh",
    "meter_box":         "single phase energy meter box plastic",
    "multiplug_5in1":    "5 in 1 multi plug white 6A india three pin",
    "socket_5pin":       "5 pin multi plug socket electrical india",
    "socket_5pin_aastha": "aastha multi plug 5 pin socket",
    "tape_pvc":          "stronx pvc electrical insulation tape roll",
    "screws_steel":      "steel screws box 100 pcs wood screw",
    "screws_brass":      "brass wood screws pack",
    # --- MCB / combined ---------------------------------------------------
    "mcb_sp":            "velox single pole MCB",
    "combined_dp":       "switch socket combined unit white 6A india plate",
    "combined_5in1":     "5 in 1 combined switch socket box modular",
    "combined_ss":       "stainless steel combined switch socket box",
    # --- LED --------------------------------------------------------------
    "bulb_9w":           "Magik Grande 9W LED bulb",
    "bulb_12w":          "Magik Grande 12W LED bulb",
    "bulb_15w":          "Magik Grande 15W LED bulb",
    "bulb_17w":          "Magik Grande 17W LED bulb",
    "bulb_20w":          "Magik Grande LED bulb 20 watt",
    "bulb_23w":          "Magik Grande 23W LED bulb",
    "bulb_30w":          "Magik 30W Power Plus LED bulb high wattage",
    "bulb_40w":          "Magik 40W Power Plus LED bulb high wattage",
    "bulb_50w":          "Magik 50W Power Plus LED bulb high wattage",
    "panel_9w":          "9W slim LED panel light round ceiling",
    "panel_12w":         "12W slim LED panel light ceiling",
    "batten_20w":        "Ultima square sleek 20W LED batten tube light",
    "downlight_24w":     "24W round surface LED downlight white",
    "downlight_36w":     "36W LED down lighter",
    "downlight_40w":     "40W LED down lighter",
    # --- premium modular / piano -----------------------------------------
    "mod_switch":        "pritam modular switch white 6A one way",
    "mod_socket":        "pritam modular 3 pin socket white 6A",
    "mod_socket_2in1":   "2 in 1 modular socket white 6A",
    "mod_indicator":     "modular neon indicator white electrical",
    "mod_2way":          "modular 2 way switch white 6A",
    "mod_bell":          "modular bell push switch white",
    "mod_socket_16a":    "16A modular socket white heavy duty",
    "mod_switch_16a":    "16A modular switch white heavy duty",
    "mod_regulator":     "modular fan regulator white 5 step",
    "mod_ac_switch":     "20A AC modular switch with indicator dp",
    "piano_switch":      "piano type electrical switch 6A white",
    "piano_socket":      "piano type 3 pin socket 6A",
    "piano_socket_2in1": "2 in 1 socket electrical india white piano type",
    "piano_indicator":   "piano type neon indicator electrical",
    "piano_2way":        "piano type 2 way switch",
    "piano_bell":        "piano bell push switch",
    "piano_socket_16a":  "16A 3 pin socket white electrical india power",
    "piano_switch_16a":  "16A switch white piano electrical india",
    "piano_regulator":   "step type ceiling fan regulator surface piano",
    # --- PRITAM boxes & plates -------------------------------------------
    "modbox_2":          "pritam modular surface box 2 module",
    "modbox_3":          "pritam modular surface box 3 module",
    "modbox_4":          "pritam modular surface box 4 module",
    "modbox_6":          "pritam modular surface box 6 module",
    "modbox_8":          "pritam premium modular surface box 8 module",
    "modbox_12":         "pritam premium modular surface box 12 module",
    "plate_2":           "modular cover plate 2 module white",
    "plate_3":           "modular cover plate 3 module white",
    "plate_4":           "modular cover plate 4 module white",
    "plate_6":           "modular cover plate 6 module white",
    "plate_8":           "modular front plate 8 module white",
    "plate_12":          "modular front plate 12 module white",
    # --- Alfa normal series ----------------------------------------------
    "alfa_switch_16a":   "16A power switch piano type white india",
    "alfa_socket_16a":   "16A 3 pin socket piano type white",
    "alfa_3in1":         "3 in 1 combined socket 6A electrical",
    "alfa_fuse":         "kit kat fuse 16A porcelain",
    "alfa_plug_16a":     "16A 3 pin top plug electrical white",
    "alfa_plug_6a":      "6A 3 pin top plug electrical white",
    "alfa_indicator":    "neon indicator point electrical white",
    "alfa_bell":         "bell push switch 6A white",
    "alfa_flush_2in1":   "2 in 1 socket 6A white electrical india flush",
    "alfa_2way":         "2 way switch 6A piano white",
    "alfa_1way":         "1 way switch 6A piano white",
    "alfa_multiplug":    "6A 16A multi plug adaptor 3 pin",
    # --- wires / clips / hardware ----------------------------------------
    "wire_zg":           "1.5 sq mm FR PVC house wire coil yellow",
    "wire_rkgold_15":    "RK Gold cables 1.5 sq mm wire",
    "wire_rkgold_10":    "RK Gold house wire coil FR PVC",
    "clip_conduit":      "PVC conduit pipe clip with nail 20mm",
    "clip_wire":         "cable wire clips with nail packet electrical",
    "clip_concrete":     "concrete cable clips with steel nail packet",
    "casing_pins":       "casing capping pins nails packet electrical",
    "clip_link":         "link clip 5mm electrical wiring",
    "wall_plugs":        "plastic wall plug gitti screw grip packet",
    # --- cords / holders / ties -------------------------------------------
    "coil_2376":         "23/76 flat twin core flexible cable coil",
    "coil_2336":         "star flex 23/36 flexible wire coil",
    "coil_1436":         "14/36 flexible twin twisted wire coil",
    "coil_4076":         "40/76 flexible copper cable coil submersible",
    "coil_1440":         "14/40 flexible wire twin twisted coil india",
    "coil_2340":         "23/40 flexible twin wire coil india",
    "coil_075":          "0.75 sqmm single core flexible cable coil",
    "poly_roll":         "packing polythene roll industrial",
    "insul_caps":        "ceiling rose insulation dome cap electrical",
    "holder_black":      "bakelite pendant lamp holder black",
    "holder_white":      "pendant lamp holder white plastic",
    "holder_angle":      "angle batten lamp holder white",
    "ties_100":          "nylon cable ties 100mm packet white",
    "ties_150":          "nylon cable ties 150mm packet",
    "ties_200":          "nylon cable ties 200mm packet",
    "ties_250":          "nylon cable ties 250mm packet white",
    # --- joy lights / decorative ------------------------------------------
    "joy_conn":          "male female joy connector series light",
    "asta_2pin":         "2 pin male top plug electrical india",
    "asta_mf_socket":    "male female socket top plug electrical india white",
    "bed_switch_aastha": "aastha bed switch hanging",
    "plug_sl":           "6A single line top plug electrical",
    "fan_reg_aastha":    "surface step type fan regulator electrical",
    "florex_multiplug":  "multi plug 3 pin socket adaptor 5A 15A india",
    "bed_switch_royal":  "royal bed switch hanging electrical",
    "plug_16a_power":    "16A 3 pin power plug top white",
    "plug_6a_std":       "aastha 2 pin top plug",
    "multiplug_616":     "6-16A combined multi plug travel adaptor",
    # --- counter stock / extensions ---------------------------------------
    "heera_ext_8":       "heera extension cord board",
    "heera_ext_4":       "extension cord flex box 4 meter white india",
    "heera_ext_3in1":    "3 in 1 extension cord electrical india",
    "polonix_bed":       "polonix bed switch",
    "aastha_holder":     "pendant lamp holder white 6A india electrical",
    "ceiling_rose":      "ceiling rose 2 plate white electrical",
    "changeover":        "32A changeover switch double throw",
    "tester_digital":    "digital voltage tester screwdriver LCD",
    "tester_std":        "line tester screwdriver electrical 500V",
    "flush_switch_blk":  "flush type switch black electrical 6A",
    "flush_socket_blk":  "3 pin flush socket black 6A",
    "neon_ind_white":    "neon indicator point white electrical india piano",
    "neon_ind_black":    "neon indicator lamp black electrical india",
    "flush_switch_wht":  "flush type piano switch white 6A",
    "wiring_blocks":     "chocolate block PVC wire connector strip",
}

ITEM_PHOTO = {
    # Section 1
    "32A TPN Main Switch": "main_switch_32a",
    "16A SPN Main Switch": "main_switch_16a",
    "LCD Digital Energy Meter": "energy_meter",
    "Single Phase Meter Box": "meter_box",
    "5-in-1 Multi-plug Adaptor": "multiplug_5in1",
    "5 Pin Multi Socket (Standard)": "socket_5pin",
    "5 Pin Multi Socket (Premium)": "socket_5pin_aastha",
    "PVC Insulation Tape": "tape_pvc",
    "25MM Steel Screws": "screws_steel",
    "35MM Steel Screws": "screws_steel",
    "16MM Steel Screws": "screws_steel",
    "1.5 Inch Brass Screws": "screws_brass",
    "1 Inch Brass Screws": "screws_brass",
    # Section 2
    "Single Pole (SP) MCB — Silk Series": "mcb_sp",
    "Double Pole (DP) Combined Switch Box": "combined_dp",
    "5-in-1 Modular Combined Box": "combined_5in1",
    "S.S. Combined Box / Switch Assembly": "combined_ss",
    # Section 3
    "9W LED Bulb": "bulb_9w",
    "12W LED Bulb": "bulb_12w",
    "15W LED Bulb": "bulb_15w",
    "17W LED Bulb": "bulb_17w",
    "20W LED Bulb": "bulb_20w",
    "23W LED Bulb": "bulb_23w",
    "30W High-Wattage LED Bulb": "bulb_30w",
    "40W High-Wattage LED Bulb": "bulb_40w",
    "50W High-Wattage LED Bulb": "bulb_50w",
    "9W Slim LED Panel Light (AC)": "panel_9w",
    "12W Slim LED Panel Light": "panel_12w",
    "20W LED Tube Light / Batten": "batten_20w",
    # batten_20w/24w/36w/40w are cropped from the shop's own photos, not
    # fetched from the web — see the batten uploads from 20-Jul-2026
    "24W LED Batten (Maximo Prime NEO)": "batten_24w",
    "36W LED Batten (Maximo Prime NEO)": "batten_36w",
    "40W LED Batten (Maximo Ultra Prime)": "batten_40w",
    "24W LED Downlight (DO)": "downlight_24w",
    "36W LED Downlight (DO)": "downlight_36w",
    "40W LED Downlight (DO)": "downlight_40w",
    # Section 4
    "Modular Switch (White)": "mod_switch",
    "Modular Socket (White)": "mod_socket",
    "2-in-1 Modular Socket (White)": "mod_socket_2in1",
    "Modular Indicator Unit (White)": "mod_indicator",
    "2-Way Modular Switch (White)": "mod_2way",
    "Modular Bell Push Switch (White)": "mod_bell",
    "16A Heavy-Duty Modular Socket": "mod_socket_16a",
    "16A Heavy-Duty Modular Switch": "mod_switch_16a",
    "Modular Fan Regulator (White)": "mod_regulator",
    "Modular A/C Starter Switch": "mod_ac_switch",
    "Piano Switch (Silver Line Series)": "piano_switch",
    "Standard Piano Socket": "piano_socket",
    "2-in-1 Piano Socket": "piano_socket_2in1",
    "Piano Indicator Unit": "alfa_indicator",
    "2-Way Piano Switch": "piano_2way",
    "Piano Bell Push Switch": "piano_bell",
    "16A Heavy-Duty Piano Socket": "piano_socket_16a",
    "16A Heavy-Duty Piano Switch": "piano_switch_16a",
    "Fan Regulator (Piano Style)": "piano_regulator",
    # Section 5
    "2-Module Modular Box": "modbox_2",
    "3-Module Modular Box": "modbox_3",
    "4-Module Modular Box": "modbox_4",
    "6-Module Modular Box": "modbox_6",
    "8-Module Modular Box": "modbox_8",
    "12-Module Modular Box": "modbox_12",
    "2-Module Cover Plate": "plate_2",
    "3-Module Cover Plate": "plate_3",
    "4-Module Cover Plate": "plate_4",
    "6-Module Cover Plate": "plate_6",
    "8-Module Cover Plate": "plate_8",
    "12-Module Cover Plate": "plate_12",
    # Section 6
    "16A Piano Switch (Ritam)": "alfa_switch_16a",
    "16A Piano Socket (Ritam)": "alfa_socket_16a",
    "6A 3-in-1 Combined Socket": "alfa_3in1",
    "10A Modular Kit-Kat Fuse Unit": "alfa_fuse",
    "16A 3-Pin Top Plug": "alfa_plug_16a",
    "6A 3-Pin Top Plug": "alfa_plug_6a",
    "Standard Neon Indicator": "alfa_indicator",
    "Standard Bell Push Switch": "alfa_bell",
    "2-in-1 Flush Socket Unit": "alfa_flush_2in1",
    "2-Way Light Switch (6A)": "alfa_2way",
    "1-Way Light Switch (6A)": "alfa_1way",
    "6-16A Multi-plug Heavy Adaptor": "alfa_multiplug",
    # Section 7
    "1.5 SQMM Copper FR Wire (Z.G.)": "wire_zg",
    "1.5 SQMM Copper FR Wire (RK Gold)": "wire_rkgold_15",
    "1.0 SQMM Copper FR Wire (RK Gold)": "wire_rkgold_10",
    "25MM Heavy Conduit Clips": "clip_conduit",
    "20MM Heavy Conduit Clips": "clip_conduit",
    "16MM Heavy Conduit Clips": "clip_conduit",
    "14MM Wire Clips": "clip_wire",
    "12MM Wire Clips": "clip_wire",
    "10MM Wire Clips": "clip_wire",
    "8MM Concrete Wire Clips": "clip_concrete",
    "7MM Concrete Wire Clips": "clip_concrete",
    "6MM Concrete Wire Clips": "clip_concrete",
    "Steel Casing Pins / Nails": "casing_pins",
    "5MM Link Clips": "clip_link",
    "Plastic Wall Plugs / Gillis": "wall_plugs",
    # Section 8
    "23/76 Twin Flat Flexible Wire": "coil_2376",
    "23/36 Multi-strand Flex Cord": "coil_2336",
    "14/36 Standard Flexible Wire": "coil_1436",
    "40/76 Heavy Duty Submersible Cord": "coil_4076",
    "14/40 Super-fine Binding/Flex Wire": "coil_1440",
    "23/40 Mid-gauge Industrial Flex": "coil_2340",
    "0.75 SQMM Single Core Flex Cable": "coil_075",
    "Industrial Polythene Roll": "poly_roll",
    "2-in-1 Top Insulation Cap": "insul_caps",
    "Pendant Lamp Holder (Bakelite Black)": "holder_black",
    "Pendant Lamp Holder (Standard White)": "holder_white",
    "Angle / Batten Holder Base": "holder_angle",
    "100mm Nylon Cable Ties": "ties_100",
    "150mm Nylon Cable Ties": "ties_150",
    "200mm Nylon Cable Ties": "ties_200",
    "250mm Nylon Cable Ties": "ties_250",
    # Section 9
    "Male-Female Joy Light Connectors": "joy_conn",
    "2-in-1 Asta Plugs / Male Pins": "asta_2pin",
    "Male-Female Assa Industrial Sockets": "asta_mf_socket",
    "Bed Hanging Switches (Assa)": "bed_switch_aastha",
    "Single Line (S/L) Top Plug 6A": "plug_sl",
    "Stepped Fan Regulator (Assa)": "fan_reg_aastha",
    "5-15A Multi-plug Universal Adaptor": "florex_multiplug",
    "Royal Hanging Bed Switches": "bed_switch_royal",
    "16A 3-Pin Power Top Plug": "plug_16a_power",
    "6A 3-Pin Standard Top Plug": "alfa_plug_6a",
    "6-16A Combined Multi-plug Adaptor": "multiplug_616",
    # Section 10
    "8-Meter Extension Flex Box (White)": "heera_ext_8",
    "4-Meter Extension Flex Box (White)": "heera_ext_8",
    "3-in-1 Combined Extension Cord": "heera_ext_8",
    "Polonix Bed Switches (Heavy Duty)": "polonix_bed",
    "Asta Premium Pendant Holders": "aastha_holder",
    "Molded Ceiling Roses (White)": "ceiling_rose",
    "32A Dual-Source Changeover Switch": "changeover",
    "Digital Line Neon Testers": "tester_digital",
    "Standard Insulation Line Testers": "tester_std",
    "6A Flush Switches (Black Series)": "flush_switch_blk",
    "6A Flush Sockets (Black Series)": "flush_socket_blk",
    "Counter Neon Indicator (White)": "neon_ind_white",
    "Counter Neon Indicator (Black)": "neon_ind_black",
    "6A Flush Switches (White Series)": "flush_switch_wht",
    "Parallel Wiring Blocks / Connectors": "wiring_blocks",
    # --- stock added 26-Jul-2026; every photo below is cropped from the
    # shop's own shelf pictures, not fetched from the web -----------------
    "2-Way Nano Switch Board": "board_2nano",
    "3-Way Nano Switch Board": "board_3nano",
    "4-Way Nano Switch Board": "board_4nano",
    "6-Way Nano Switch Board": "board_6nano",
    "7-Way Nano Switch Board": "board_7way",
    "8-Way Nano Switch Board (Heavy Duty)": "board_8way",
    "6x4 Switch Board (Heavy Duty)": "board_6x4",
    "8x6 Switch Board": "board_8x6",
    "3x3 Switch Board": "board_3x3",
    "2x4x7 Board (4-Cut Plain)": "board_2x4x7",
    "8/10 Way Switch Board (Aavtar)": "board_aavtar810",
    "8x6 Plain Switch Board (Aavtar)": "board_aavtar8x6",
    "95mm Round Sheet (Neon Glow)": "round_sheet",
    "85mm Round Sheet (Neon Glow)": "round_sheet",
    "MCB Distribution Box (Aashiyana)": "mcb_box_aashiyana",
    "2 Modular Surface Gang Box": "gangbox_2",
    "3 Modular Surface Gang Box": "gangbox_3",
    "4 Modular Surface Gang Box": "gangbox_4",
    "6 Modular Surface Gang Box": "gangbox_6",
    "8 Modular Surface Gang Box": "gangbox_8",
    "12 Modular Surface Gang Box": "gangbox_12",
    "1 Inch Casing Internal Bend": "casing_internal",
    "1 Inch Casing External Bend": "casing_external",
    "1 Inch Casing Elbow": "casing_elbow1in",
    "1 Inch Casing Tee": "casing_tee1in",
    "20x25mm Casing Elbow (3/4 Inch)": "casing_elbow2025",
    "20x25mm Casing Tee (3/4 Inch)": "casing_tee2025",
    "20x25mm Casing Internal Bend (3/4 Inch)": "casing_internal2025",
    "20x25mm Casing External Angle (3/4 Inch)": "casing_extangle2025",
    "PVC Casing-Capping Length": "casing_capping",
    "1 Module MS Concealed Box": "mbox_gi",
    "2 Module MS Concealed Box": "mbox_gi",
    "3 Module MS Concealed Box": "mbox_golden",
    "4 Module MS Concealed Box": "mbox_golden",
    "6 Module MS Concealed Box": "mbox_golden",
    "8 Module MS Concealed Box": "mbox_gi",
    "Round Metal Fan Box": "fanbox_round",
    "16mm Corrugated Flex Pipe": "chamak_range",
    "20mm Corrugated Flex Pipe": "chamak_white",
    "25mm Corrugated Flex Pipe": "chamak_grey",
    "HDPE Water Pipe (Bandhan Plus)": "hdpe_bandhan",
    "HDPE Water Pipe (Aashiyana)": "hdpe_aashiyana",
    "7/20 Copper Wire Coil": "wire_720",
    "4 MM Copper Wire Coil": "wire_4mm",
    "6 MM Copper Wire Coil": "wire_6mm",
    "8 MM Copper Wire Coil": "wire_8mm",
    "10 MM Copper Wire Coil": "wire_10mm",
    "Kamla Bed Switch": "kamla_bedswitch",
    "Kamla Ultra White 5-Pin Socket": "kamla_socket",
    "April Hanging Bed Switch": "bedswitch_april",
    "Texas Single Adaptor (2A)": "adaptor_texas",
    "Changeover Switch (Mini Knife Type DP)": "changeover_hotsea",
    "Power Strip / Spike Guard (6+1)": "powerstrip_ke",
}
